homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 149
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.30.32.0/23

# Enables configuration UI
config:

#enables HASSIO
hassio:

system_health:

mobile_app:

cloud: !include cloud.yaml

http:
  #api_password: !secret http_api_password
  trusted_networks:

  #ip_ban_enabled: True
  #login_attempts_threshold: 5
  base_url: hassio.home.goodbar.io:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

panel_iframe: !include panels.yaml


recorder:
#  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 3
  exclude:
    entities:
      - sensor.weather_icon
      - sensor.weather_summary
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.ram_use
      - sensor.date_time
      - sensor.date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time_date
      - sensor.date 
      - sensor.average_load_15m
      - sensor.average_load_5m 
      - sensor.worldclock_sensor
      - sensor.homeassistant_uptime
      - sensor.homeassistant_version
      - sensor.time
    domains:
      - automation
      - weblink
      - updater


# View all events in a logbook
logbook:


# Track the sun
sun:

#FFMpeg Enable
ffmpeg:

# Text to speech
tts:
  platform: google_translate

##Includes
group: !include_dir_merge_named groups/
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
camera: !include camera.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
#input_select: !include_dir_merge_named input_select
sensor: !include_dir_merge_list sensor
light: !include_dir_merge_list light
# remote: !include remote.yaml
  

hue:
  bridges:
    - host: 192.168.2.39
      allow_hue_groups: false
        
vera:
  vera_controller_url: http://192.168.2.38:3480/

ecobee:
  api_key: !secret ecobee_api_key

ios:

logger: 
  default: info
  logs:
#    homeassistant.core: warn
#    homeassistant.components.automation: warn
#    homeassistant.components.device_tracker: warn
#    homeassistant.components.discovery: warn
#    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
#    homeassistant.components.recorder: warn
    homeassistant.components.zwave: info
    homeassistant.helpers.script: info
#    homeassistant.helpers.entity: critical
    homeassistant.exceptions: info
    py.warnings: error
    root: warn

frontend: 
  themes: !include_dir_merge_named themes

api:

homekit: !include homekit.yaml

mqtt:
  broker: 172.17.0.1
  username: !secret mqtt_user
  password: !secret mqtt_password

wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

octoprint: !include octoprint.yaml

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: telegram
    platform: telegram
    chat_id: 218698090

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 218698090

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload