- platform: darksky
  name: Weather
  api_key: !secret skydark 
  monitored_conditions:
    - apparent_temperature
    - apparent_temperature_max
    - apparent_temperature_min
    - temperature
    - humidity
    - icon
    - precip_intensity
    - precip_probability
    - summary
    - wind_speed
    - hourly_summary
    - daily_summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - ozone
  update_interval: '00:30'