- platform: darksky
  name: Weather
  api_key: !secret skydark 
  monitored_conditions:
    - temperature
    - apparent_temperature
    - temperature_high
    - temperature_low
    - humidity
    - icon
    - precip_intensity
    - precip_probability
    - summary
    - wind_speed
    - hourly_summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - ozone
    - moon_phase
  update_interval:
    minutes: 30