- alias: Daily Backup at 3 AM
  trigger:
    platform: time
    at: '3:00:00'
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
#  - service: notify.slack_notify
#    data_template:
#      message: Creating backup named "Automated Backup {{ now().strftime('%Y-%m-%d') }}"
- alias: Daily upload to dropbox at 4 AM
  trigger:
    platform: time
    at: '4:00:00'
  action:
  - service: hassio.addon_stdin
    data_template:
      name: {"addon":"7be23ff5_dropbox_sync","input":{"command":"upload"}}